### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by andreayaya** [heyMP/digitalmeasures#6]
I stumbled across this while searching for a way to integrate Digital Measures with Drupal.  I am not sure how this works, as I installed the module but not sure what I can do to get the data from Digital Measures into Drupal.  Any chance you could provide an example for use?

**Comment by heyMP** [comment]
This is an API module for Drupal, so it doesn't have any OOTB functionality yet.  What does do is give you the ability to retrieve a list of active searchable indexes from Digital Measures by calling the `digitalmeasures_digitalmeasures_get_indexes()` function and the ability to search on those indexes with `digitalmeasures_digitalmeasures_get_schemadata()`.

I have some instructions on the readme page on how to include your Digital Measures credentials as well as how to retrieve data using drush.

**Comment by andreayaya** [comment]
It would be great if this could integrate with Feeds module to pull data from Digital Measures into Drupal.  I will look further into the the calls, but I have never coded a module.  Will you be developing this module further?

**Comment by heyMP** [comment]
Feeds integration might be possible.  I don't work with Digital Measure anymore so I can't say when I'll be able to add features to it unfortunately.  What I can do is put this on Drupal.org and see if anyone would like to take over the development.

**Comment by andreayaya** [comment]
Thanks!  And so you know, any authentication I've tried with Digital Measures and Feeds has produced errors due to the / that Digital Measures places in the username.
